version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      # # build the application image
      # - run: docker build -t edbordin/summon-fpga-tools:$CIRCLE_BRANCH .
      # - run: |
      #     echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      # # deploy the image
      # - run: docker push edbordin/summon-fpga-tools:$CIRCLE_BRANCH
      - run: bash run-sft.sh
      - store_artifacts:
          path: /root/sft/
      - store_artifacts:
          path: /root/symbiflow-nightly.tar.gz
          destination: symbiflow-nightly.tar.gz
